title: Nighthawk-Pages
description: "November 2023 to February 2024"
owner_name: Rayane Souissi
github_username: rayanesouuuu1234
github_repo: "student02"
baseurl: "/student02"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/student02"}
    - { platform: github, user_url: "https://github.com/rayanesouuuu1234"}
    - { platform: github, user_url: "https://github.com/rayanesouuuu1234"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
